#region Using Directives

using System;
using System.Collections.Generic;
using System.Numerics;

#endregion

namespace Project.Euler.Problems
{
    public class Problem029 : IProblem
    {
        public int ProblemNumber
        {
            get { return 29; }
        }

        public string Description
        {
            get { return "How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?"; }
        }

        public override string ToString()
        {
            return String.Format("Problem {0:000}", ProblemNumber);
        }

        public long Solve()
        {
            var terms = new List<BigInteger>();
            for (int a = 2; a <= 100; a++)
            {
                for (int b = 2; b <= 100; b++)
                {
                    BigInteger term = BigInteger.Pow( a, b );
                    if( !terms.Contains(term))
                        terms.Add(term);
                }
            }
            return terms.Count;
        }
    }
}
